### ISSUE TITLE
Random button area to click

### ISSUE THREAD

**Issue by zoiodelula** [DedInc/emunium#1]
Hello, its possible to randomize the cordinates inside the element? If the clicks goes always on certer its easy to detect

**Comment by DedInc** [comment]
You can use offsets for reach it:

```python
import random
from emunium import EmuniumSelenium

driver = webdriver.Chrome()
wait = WebDriverWait(driver, 10)
emunium = EmuniumSelenium(driver)

driver.get('https://duckduckgo.com/')

element = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, '[data-state="suggesting"]')))

# coordinate randomization with respect to the center
emunium.find_and_move(element, click=True, offset_x=random.uniform(0.0, 1.5), offset_y=random.uniform(0.0, 1.5))
```

**Comment by zoiodelula** [comment]
Okay, can we use the area of the button instead of center? It look more human, i know where but dont know how to do it,  var element = arguments[0];
            var rect = element.getBoundingClientRect();
            var centerX = rect.left + rect.width / 2 + window.scrollX;
            var centerY = rect.top + rect.height / 2 + (window.scrollY || window.pageYOffset) + (screen.height - window.innerHeight) / 1.5;
