### ISSUE TITLE
I tried script and it doesnt work

### ISSUE THREAD

**Issue by deschandhok24** [DedInc/emunium#6]
I tried the script for playwright and selenium in the examples you show and it doesnt work. It goes to wrong element or raises  ImageNotFoundException due to confidence being to low.

**Comment by deschandhok24** [comment]
https://github.com/DedInc/emunium/assets/33607373/49b5afcc-f75e-4810-a681-c21fa0245a85

**Comment by deschandhok24** [comment]
https://github.com/DedInc/emunium/assets/33607373/cba8a471-4387-4d39-a01f-4b4d51725bbd

**Comment by nnishad** [comment]
`async def _get_browser_properties_if_not_found(self, screenshot_func):
        if not self.browser_offsets or not self.browser_inner_window:
            with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as temp_file:
                temp_screen_path = temp_file.name
            if asyncio.iscoroutinefunction(screenshot_func):
                await screenshot_func(temp_screen_path)
            else:
                screenshot_func(temp_screen_path)

            #location = pyautogui.locateOnScreen(temp_screen_path, confidence=0.0)
            self.browser_offsets = (
                location.left,
                location.top,
            )
            self.browser_inner_window = get_image_size(temp_screen_path)
            os.remove(temp_screen_path)`

**Comment by nnishad** [comment]
`async def _get_browser_properties_if_not_found(self, screenshot_func):
        if not self.browser_offsets or not self.browser_inner_window:
            with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as temp_file:
                temp_screen_path = temp_file.name
            if asyncio.iscoroutinefunction(screenshot_func):
                await screenshot_func(temp_screen_path)
            else:
                screenshot_func(temp_screen_path)

            location = pyautogui.locateOnScreen(temp_screen_path, confidence=0.0)
            self.browser_offsets = (
                location.left,
                location.top,
            )
            self.browser_inner_window = get_image_size(temp_screen_path)
            os.remove(temp_screen_path)`

Make confidence to 0.0 . This is a hack. not sure what exactly this screenshot is required for apart from screensize. Developer has used very clever way of getting offset of browser.
